/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Model.Account;
import Model.Right;
import Serv_impl.Account_serv_impl;
import Serv_interface.Account_serv_interface;
import Tool.ErrorException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author mojeb
 */
public class LogIn extends javax.swing.JDialog {

    /**
     * Creates new form LogIn
     */
    private JMenu hr_menu1;
    private JMenu hr_menu2;
    private JMenu hr_menu3;
    private JMenu hr_menu4;
    
    private JMenuItem logIn;
    private JMenuItem logOut;
    
    private JMenuItem sys_lib;
    private JMenuItem user_lib;
    private JMenuItem manage_emp;
    private JMenuItem manage_accnt;
    private JMenuItem manage_office;
    private JMenuItem database;
    
    private JMenuItem so;
    private JMenuItem memo;
    private JMenuItem oo;
    
    private JMenuItem riv;
    private JMenuItem po;
    private JMenuItem list;
    private JMenuItem print;
    
    private JMenuItem pass;
    
    private Account_serv_interface aServ;
    private ArrayList<Right> rList = null;
    
    public LogIn(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Log In");
        
        aServ = new Account_serv_impl();
    }
    
    public void setGSU(JMenuItem riv, JMenuItem po, JMenuItem list,
            JMenuItem print){
        this.riv = riv;
        this.po = po;
        this.list = list;
        this.print = print;
    }
    
    public void setHRU(JMenu hr_menu1, JMenu hr_menu2, JMenu hr_menu3, 
            JMenu hr_menu4){
        this.hr_menu1 = hr_menu1;
        this.hr_menu2 = hr_menu2;
        this.hr_menu3 = hr_menu3;
        this.hr_menu4 = hr_menu4;
    }
    
    public void setAdmin(JMenuItem sys_lib, JMenuItem user_lib, JMenuItem manage_emp,
            JMenuItem manage_accnt, JMenuItem manage_office, JMenuItem database){
        this.sys_lib = sys_lib;
        this.user_lib = user_lib;
        this.manage_emp = manage_emp;
        this.manage_accnt = manage_accnt;
        this.manage_office = manage_office;
        this.database = database;
    }
    
    public void setLogButton(JMenuItem logIn, JMenuItem logOut){
        this.logIn = logIn;
        this.logOut = logOut;
    }
    
    public void setORVP(JMenuItem so, JMenuItem memo, JMenuItem oo){
        this.so = so;
        this.memo = memo;
        this.oo = oo;
    }
    
    public void setPassword(JMenuItem pass){
        this.pass = pass;
    }
    
    private void examine_rights(){
        if(rList != null){
            ArrayList<String> rlist = new ArrayList<String>();
            for(Right r : rList){
                if(r.getStatus().equals("Active"))
                    rlist.add(r.getRight());
            }
            
            if(rlist.contains("HRU Personnel")){
                this.hr_menu1.setEnabled(true);
                this.hr_menu2.setEnabled(true);
                this.hr_menu3.setEnabled(true);
                this.hr_menu4.setEnabled(true);
            }
            
            if(rlist.contains("Administrator")){
                this.sys_lib.setEnabled(true);
                this.user_lib.setEnabled(true);
                this.manage_emp.setEnabled(true);
                this.manage_accnt.setEnabled(true);
                this.manage_office.setEnabled(true);
                this.database.setEnabled(true);
            }
            
            if(rlist.contains("ORVP Personnel")){
                this.so.setEnabled(true);
                this.memo.setEnabled(true);
                this.oo.setEnabled(true);
            }
            
            if(rlist.contains("GSU Personnel")){
                this.riv.setEnabled(true);
                this.po.setEnabled(true);
                this.list.setEnabled(true);
                this.print.setEnabled(true);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Username:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Password:");

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        jPasswordField1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/group_key.png"))); // NOI18N
        jButton1.setText("Log In");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/cancel16.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                        .addComponent(jTextField1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = jTextField1.getText();
        String password = new String(jPasswordField1.getPassword());
        if(username.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Error! Username and password required.", 
                    "Error Message", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                Account acc = aServ.getAccount_emp_id(username);
                if(acc == null){
                    JOptionPane.showMessageDialog(this, "Error! Username "+username+" doesn't exists.", 
                        "Error Message", JOptionPane.ERROR_MESSAGE);
                }else{
                    if(acc.getPassword().equals(password)){
                        this.logIn.setEnabled(false);
                        this.logOut.setEnabled(true);
                        this.pass.setEnabled(true);
                        rList = aServ.getRight_emp_id(acc.getEmp().getEmp_id());
                        examine_rights();
                        Main_Window.account = acc;
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(this, "Error! Incorrect password.", 
                                    "Error Message", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }catch(ErrorException ex){
            }catch(FileNotFoundException ex){
            }catch(IOException ex){}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        jButton1.doClick();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the dialog
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                LogIn dialog = new LogIn(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
